version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ukoray_development

  cache:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
